# Environment specific settings can be defined in /config/environments/[RAILS_ENV].yml

app: 
  name: &app_name Signage

security:
  key_path: /home/anoble/Projects/Biola/THI Eval/Certs/thi-eval@biola.edu.pem
  key_password: nOoUnhDh9GOJWDwjWJyhK
  cert_path: /home/anoble/Projects/Biola/THI Eval/Certs/thi-eval@biola.edu.pem
  verify_ssl: false
  https_available: false
  
  login:
    required: true # for reporting only, doesn't turn authentication on or off
    forgot_url: "https://login.biola.edu/reset-password"
    auto_create_users: false
    allow_bypass: false # should only be usid in development
    allowed_roles:
    - admin
    - manager
    impersonation:
      enable: true
      allowed_groups:
      - analysts
      allowed_roles:
      
  users:
    auto_update: true
      
  roles:
    base_entitlement: "biola:sign-manager:"
    include_affiliations: true
    
  session:
    key: _sign_manager_session
    secret: 92e7b69266b365a7e438a4ea5a6b66734162d864b945f581e631b7e5f607d7209b8c344049f33bf388d34c0c6a1fe980af7e351e7cbf6ed0e15e93664f8be372
    # Run rake secret to generate a new secret string
    
email:
  from: no-reply@biola.edu
  developer: adam.crownoble@biola.edu
  smtp:
    server: smtp.gmail.com
    domain: localhost # Used in HELO handshaking
    port: 587
    enable_tls: true
    auth_type: login
    username: wssvc@biola.edu
    password: lksj48nHewngh
    
ui:
  menu: # accepts text, url, controller, action and css_class
  - controller: dashboard
    action: show
  - controller: slides
  - controller: signs
  menu_aside:
  - controller: pages
    action: feedback
    text: Feedback
    css_class: feedback
  - controller: documents
    css_class: documents
  - controller: announcements
    css_class: announcements
  admin_menu:
  - controller: users
  - url: http://apps.biola.edu/access/services/sign-manager
    text: Access
    css_class: access
  - url: https://www.google.com/analytics/reporting/
    text: Analytics
    css_class: analytics
  - controller: info
    action: performance
    text: Performance
  - controller: info
    action: database
    text: Database
  - controller: info
    action: config
    text: Config
  pagination:
    per_page: 10

feedback:
  domain: techcommunity.biola.edu
  fastpass:
    key: tpu96tbwh71y
    secret: mk4zvu1icy7y3vtvpk88je8dehs6t7oa
  widget_id: 164567e5d3
  company: biola_it
  product: 
  custom_css: http://apps.biola.edu/media/css/getsatisfaction-feedback.css
  default_tab: question
  question_limit: 5

google_analytics:
  enabled: true
  web_property_id: UA-95199-28
  
routing:
  default:
    controller: dashboard
    action: show
    
developer:
  title: Information Technology
  homepage: http://offices.biola.edu/it/
  
# For more info: http://github.com/newrelic/rpm/blob/944dc0a6c9c8fe8fc2771e58d07aa8a30d00650d/newrelic.yml
newrelic:
  license_key: 'aae818a689f464250d29dbe1ba028beae7193b26'
  app_name: *app_name
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false
  apdex_t: 0.5 
  capture_params: false
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
  error_collector:
    enabled: true
    capture_source: true    
    ignore_errors: ActionController::RoutingError
  link: http://rpm.newrelic.com
