# Environment specific settings can be defined in /config/environments/[RAILS_ENV].yml

app:
  name: &app_name Signage
  host: your.server.tld
  relative_url_root: /signage # or blank if no relative root

# Overwrite this in settings.local.yml  -> rake secret
secret_token: 'c457e099cb8f80054e41dccbfefeafc222ee1bd06c68006aa807698933186c291419f490defdd0d4145e57a64d59d5045bdb8699e7bc18c8c2e2361ff0d8d81b'

urn_namespaces:
- "urn:biola:apps:sign-manager:"
- "urn:biola:apps:all:"

base_entitlement: "urn:biola:apps:sign-manager:"

cas:
  url: 'https://login.biola.edu/cas'

email:
  from: no-reply@example.com
  developer: developer@example.com
  smtp:
    server: smtp.example.com
    domain: example.com # Used in HELO handshaking
    port: 25
    enable_tls: true
    auth_type: login
    username: user@example.com
    password: '****************'

ui:
  pagination:
    per_page: 30

defaults:
  sign:
    email_frequency: 24   # in hours
  slide:
    interval: 7

google_analytics:
  enabled: true
  web_property_id: XX-00000-00

pubnub:
  enabled: false
  channel: channel_name
  publish_key: ''
  subscribe_key: ''
